tau_correlation_length = 0.5
noise_amplitude = 0.0001
num_bins = 1000
dtau = 0.05
beta = 10.0

[spectral_function]
num_distributions = 2

    [[spectral_function.distribution]]
    sigma = 0.5
    weight = 0.5
    type = "Normal"
    mu = 0.0
    [[spectral_function.distribution]]
    sigma = 0.5
    weight = 0.5
    type = "Normal"
    mu = 2.0
